package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 11 Œàðò 2014 ã. 9:08:52 MSK
*/


/* (YµµT ±
d
T Y */
public interface StationOperations 
{

  /* 'µe
  d ±  Y
  	µ
  	 phoneNum,
      VW 
  ±Y
  e
   d
  d ± Z
  W
  d W TubeCallback */
  int register (Cell.TubeCallback objRef, String phoneNum);

  /* .Zd 
  
  ±µYµ message 
   Y
  	µ fromNum  Y
  	µ toNum */
  int sendSMS (String fromNum, String toNum, String message);
} // interface StationOperations
