package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 9 Œàðò 2014 ã. 16:31:11 MSK
*/


/* (YµµT ±
d
T Y */
public interface StationOperations 
{

  /* VW 
  ±Y
  e
   d
  d ± Z
  W
  d W TubeCallback */
  int register (Cell.TubeCallback objRef, String phoneNum);

  /* .Zd 
  
  ±µYµ message 
   Y
  	µ fromNum  Y
  	µ toNum */
  int sendSMS (String fromNum, String toNum, String message);
} // interface StationOperations
