package Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 9 Œàðò 2014 ã. 16:31:11 MSK
*/


/* (YµµT ±
d
T Y */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
