package Cell;


/**
* Cell/TubeCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 11 Œàðò 2014 ã. 10:57:07 MSK
*/


/* (YµµT 
±Y
e
 d
d ± */
public interface TubeCallbackOperations 
{

  /* /Y 
  
  ±µYµ message 
   Y
  	µ fromNum */
  int sendSMS (String fromNum, String message);
  int getSMS (String fromNum, String message);
  void setRefDest (Cell.TubeCallback ref);
  Cell.TubeCallback getTubeCallback ();

  /* "µY d
  T Y
  	µ */
  String getNum ();
} // interface TubeCallbackOperations
