package Cell;


/**
* Cell/TubeCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 11 Œàðò 2014 ã. 10:57:07 MSK
*/


/* (YµµT 
±Y
e
 d
d ± */
public abstract class TubeCallbackPOA extends org.omg.PortableServer.Servant
 implements Cell.TubeCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendSMS", new java.lang.Integer (0));
    _methods.put ("getSMS", new java.lang.Integer (1));
    _methods.put ("setRefDest", new java.lang.Integer (2));
    _methods.put ("getTubeCallback", new java.lang.Integer (3));
    _methods.put ("getNum", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /* /Y 
  
  ±µYµ message 
   Y
  	µ fromNum */
       case 0:  // Cell/TubeCallback/sendSMS
       {
         String fromNum = in.read_string ();
         String message = in.read_string ();
         int $result = (int)0;
         $result = this.sendSMS (fromNum, message);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Cell/TubeCallback/getSMS
       {
         String fromNum = in.read_string ();
         String message = in.read_string ();
         int $result = (int)0;
         $result = this.getSMS (fromNum, message);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Cell/TubeCallback/setRefDest
       {
         Cell.TubeCallback ref = Cell.TubeCallbackHelper.read (in);
         this.setRefDest (ref);
         out = $rh.createReply();
         break;
       }

       case 3:  // Cell/TubeCallback/getTubeCallback
       {
         Cell.TubeCallback $result = null;
         $result = this.getTubeCallback ();
         out = $rh.createReply();
         Cell.TubeCallbackHelper.write (out, $result);
         break;
       }


  /* "µY d
  T Y
  	µ */
       case 4:  // Cell/TubeCallback/getNum
       {
         String $result = null;
         $result = this.getNum ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Cell/TubeCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TubeCallback _this() 
  {
    return TubeCallbackHelper.narrow(
    super._this_object());
  }

  public TubeCallback _this(org.omg.CORBA.ORB orb) 
  {
    return TubeCallbackHelper.narrow(
    super._this_object(orb));
  }


} // class TubeCallbackPOA
